repos:
  - repo: https://github.com/psf/black
    # black config is in pyproject.toml
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/PyCQA/flake8
    # flake8 config is in setup.cfg
    rev: 5.0.4
    hooks:
      - id: flake8
        language_version: python3.8
  - repo: https://github.com/PyCQA/isort
    # isort config is in pyproject.toml
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3.8
